USE [master]
GO

/****** Object:  Database [AccountDB_]    Script Date: 26.04.2022 14:53:44 ******/
CREATE DATABASE [AccountDB_]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AccountDB_', FILENAME = N'D:\SSMS\AccountDB_.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AccountDB__log', FILENAME = N'D:\SSMS\AccountDB__log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AccountDB_].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AccountDB_] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AccountDB_] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AccountDB_] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AccountDB_] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AccountDB_] SET ARITHABORT OFF 
GO

ALTER DATABASE [AccountDB_] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AccountDB_] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AccountDB_] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AccountDB_] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AccountDB_] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AccountDB_] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AccountDB_] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AccountDB_] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AccountDB_] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AccountDB_] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AccountDB_] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AccountDB_] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AccountDB_] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AccountDB_] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AccountDB_] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AccountDB_] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AccountDB_] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AccountDB_] SET RECOVERY FULL 
GO

ALTER DATABASE [AccountDB_] SET  MULTI_USER 
GO

ALTER DATABASE [AccountDB_] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AccountDB_] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AccountDB_] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AccountDB_] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AccountDB_] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AccountDB_] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [AccountDB_] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AccountDB_] SET  READ_WRITE 
GO


USE [AccountDB_]
GO

/****** Object:  Table [dbo].[Account]    Script Date: 26.04.2022 14:56:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Account](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](255) NOT NULL,
	[Login] [nvarchar](255) NOT NULL,
	[Password] [nvarchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Login] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


INSERT INTO AccountDB_.dbo.Account
VALUES
('Marcin','Login1','Password1'),
('Dominik','Login2','Password2'),
('Andrzej','Login3','Password3')

--should return 3 rows if it's good create database
SELECT * FROM AccountDB_.dbo.Account
